### ISSUE TITLE
Create interfaces file

### ISSUE THREAD

**Issue by patrickpiccini** [arsenypoga/python-grpc-crud#4]
It is necessary to describe to create the "interfaces" file in the documentation.
Or create the file in the repository. 

:D

**Comment by arsenypoga** [comment]
It's not a file, but a directory. I should have created it with the `.gitkeep` file in it, so it got pushed to git, and the files would be generated by following the instructions in `README`, but at the time I didn't think about that.

The purpose of this project was to be a demo for the one of my college papers.

There is one thing that I completely missed - the command in `README` for the stub generation is not entirely correct as it generates the files, but does not produce the correct import structure. Coincidentally, this also creates the directory in question.

**Comment by patrickpiccini** [comment]
Exactly... I meant directory "interfaces" hahaha.
But congratulations on the demo you created, there are few quality examples about gRPC with Python like yours. :)
